apiVersion: supply-chain.apps.tanzu.vmware.com/v1alpha1
kind: Component
metadata:
    name: stream-deployer-1.0.0
spec:
    config:
        - path: spec.streamName
          schema:
            description: |
                The name to the stram to be applied to the system.
            type: string
    description: Deploys scdf streams resources to the cluster.
    pipelineRun:
        params:
            - name: scdf-stream-name
              value: $(workload.spec.streamName)
        pipelineRef:
            name: stream-deployer
        taskRunTemplate:
            podTemplate:
                securityContext:
                    fsGroup: 1000
                    runAsGroup: 1000
                    runAsUser: 1001
        workspaces:
            - name: shared-data
              volumeClaimTemplate:
                spec:
                    accessModes:
                        - ReadWriteOnce
                    resources:
                        requests:
                            storage: 1Gi
