apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
    name: stream-deployer
spec:
    description: Deploy the stream to SCDF
    params:
        - description: Name of the stream to be deployed
          name: scdf-stream-name
          type: string
    tasks:
        - name: stream-deployer
          params:
            - name: scdf-stream-name
              value: $(params.scdf-stream-name)
          taskRef:
            kind: Task
            name: stream-deployer
          workspaces:
            - name: content
              workspace: shared-data
    workspaces:
        - description: |
            This workspace contains the cloned repo files, so they can be read by the
            next task.
          name: shared-data
