apiVersion: supply-chain.apps.tanzu.vmware.com/v1alpha1
kind: SupplyChain
metadata:
    name: webappv1
spec:
    defines:
        group: supplychains.dev.springdeveloper.com
        kind: WebAppV1
        plural: webappv1s
        version: v1alpha1
    description: Supply chain to build web app from Git and deploy it
    stages:
        - componentRef:
            name: source-git-provider-1.0.0
          name: source-git-provider
        - componentRef:
            name: buildpack-build-1.0.0
          name: buildpack-build
        - componentRef:
            name: conventions-1.0.0
          name: conventions
        - componentRef:
            name: app-config-web-1.0.0
          name: app-config-web
        - componentRef:
            name: carvel-package-1.0.0
          name: carvel-package
        - componentRef:
            name: deployer-1.0.0
          name: deployer
