apiVersion: supply-chain.apps.tanzu.vmware.com/v1alpha1
kind: SupplyChain
metadata:
    name: streamv1
spec:
    defines:
        group: supplychains.dataflow.cloud.springframework.org
        kind: StreamV1
        plural: streamv1s
        version: v1alpha1
    description: Stream stream-deployer
    stages:
        - componentRef:
            name: source-git-provider-1.0.0
          name: source-git-provider
        - componentRef:
            name: stream-deployer-1.0.0
          name: stream-deployer
